### ISSUE TITLE
[FEAT] 홈 화면 UI 생성 및 기능 연결

### ISSUE THREAD

**Issue by paengjiwoo** [jellysoo97/nanalmoa-FE#14]
## ✅ 이슈 내용

- 홈 화면 구현
  - 일간 일정 화면 구현
    - 일간뷰 날짜 선택 기능은 후순위 구현 
   - 일정 상세 화면 구현
     - 필수 입력 content 위주로 구현 

## ✅ Todos
- [X] 홈 화면 일정 뷰 선택 Tab 구현
- [X] 일간 일정 카드 컴포넌트 구현
- [X] 카테고리 태그 컴포넌트 구현
- [X] 일정 상세 화면 구현 - 필수 입력 요소 위주로
- [X] 일정 전체 조회, 상세 조회 api 연결
