### ISSUE TITLE
[FEAT] 일정 등록 폼 필드 추가

### ISSUE THREAD

**Issue by paengjiwoo** [jellysoo97/nanalmoa-FE#45]
## ✅ 이슈 내용
일정 등록 폼 필드 추가
- 메모 : 필드 추가 및 기능 연결
- 그룹 : 필드 생성 및 필요 UI 구현
- 반복 : 추가 컴포넌트 없이 임의 필드 생성

## ✅ Todos
- [X] 메모 추가 및 기능 연결
- [X] 그룹 필드 추가
- [X] 그룹 static 값으로 UI 구현
- [X] 반복 필드 생성
