### ISSUE TITLE
[FEAT] 일정 상세 페이지 수정, 삭제 기능 추가

### ISSUE THREAD

**Issue by paengjiwoo** [jellysoo97/nanalmoa-FE#46]
## ✅ 이슈 내용
- 일정 상세 페이지 노출 필드 추가
  - 시작 일자, 종료 일자, 장소, 메모
- 일정 삭제 기능 연결
  - 삭제 여부 확인하는 modal 추가
- 일정 수정 기능 연결
  - 수정 완료에 대한 피드백 제공하는 toast 추가
- 일정 수동 등록 페이지 UI/UX 수정

## ✅ Todos
- [x] 일정 상세 페이지 필드 추가
- [x] 일정 삭제 및 수정 버튼 UI 수정
- [x] 일정 삭제 기능 연결
- [x] 일정 수정 로직 작성
- [x] 일정 수동 등록 stepper 추가
