### ISSUE TITLE
[STYLE] 디자인 수정

### ISSUE THREAD

**Issue by jellysoo97** [jellysoo97/nanalmoa-FE#55]
## ✅ 이슈 내용
- 홈화면 일간뷰, 월간뷰 디자인 수정
- 일정 폼 일부 디자인 수정

## ✅ Todos
- [ ] 홈화면 탭 디자인 수정
- [ ] 홈화면 일간뷰 디자인 수정
- [ ] 홈화면 월간뷰 디자인 수정
- [ ] 일정 폼 일부 디자인 수정
