### ISSUE TITLE
[FEAT] 사진 일정 등록 페이지 ui 및 로직 추가

### ISSUE THREAD

**Issue by jellysoo97** [jellysoo97/nanalmoa-FE#58]
## ✅ 이슈 내용
- 사진 일정 등록 페이지 ui
  - step1: 등록안내
  - step2: 사진등록
  - step3: 분석결과
  - step4: 등록완료
- 사진 촬영, 파일 업로드 로직 추가
- 분석결과, 등록결과에 따른 로직 처리

## ✅ Todos
- [x] step별 ui
- [x] step별 로직 추가
- [x] 사진 촬영 로직
- [x] 파일 업로드 로직
- [x] 결과에 따른 ui 처리
