### ISSUE TITLE
[FEAT] 회원가입 ui 및 api 연동

### ISSUE THREAD

**Issue by jellysoo97** [jellysoo97/nanalmoa-FE#64]
## ✅ 이슈 내용
- 회원가입 페이지 ui
- 회원가입, 전화번호 인증, 인증코드 확인 api 연동

## ✅ Todos
- [x] 회원가입 페이지 ui
- [x] 인증 타이머 구현
- [x] 회원가입, 전화번호 인증, 인증코드 확인 api 연동
