### ISSUE TITLE
[FIX] 로그인 버그 픽스

### ISSUE THREAD

**Issue by jellysoo97** [jellysoo97/nanalmoa-FE#80]
## ✅ 이슈 내용
- 로그인 재시도 시 인증코드 타이머 버그픽스
- 인증하기 api 호출에 따른 상태 버그픽스
- validation trigger 수정
- 배포 스크립트 수정
- env 파일명 수정

## ✅ Todos
- [x] 로그인 재시도 시 인증코드 타이머 버그픽스
- [x] 인증하기 api 호출에 따른 상태 버그픽스
- [x] validation trigger 수정
- [x] 배포 스크립트 수정
- [x] env 파일명 수정
